name: LaboratoryPlugin
version: 1.0.0
main: com.example.laboratory.LaboratoryPlugin
api-version: 1.21
depend: [Nexo]
author: YourName
description: Advanced laboratory system with research and crafting

commands:
  teleport:
    description: Teleport to a specific teleporter
    usage: /teleport <id>
  radiation:
    description: Check radiation level
    usage: /radiation